### ISSUE TITLE
First layer issues with multiple object on Trident after autotune

### ISSUE THREAD

**Issue by MallocArray** [andrewmcgr/klipper_tmc_autotune#208]
Trident 300 cubed LDO Rev A Kit.  
After enabling klipper_tmc_autotune for the motors I have, if I'm printing multiple objects, the very first object's first layer looks normal.  When it moves to the first layer of the second object, it is slightly higher.  When it moves to other objects, it is even higher, eventually to the point that prints will fail.

If I comment out the autotune config section and reprint the same file, the first layer on each item is consistent across the objects.
Unsure if I've implemented something wrong.  I verified the Z-Motor models and used documentation for the other motors in my build.

Latest Klipper, Octopus 1.1 board with BigTreeTech TMC2209-v1.2

```
[autotune_tmc stepper_x]
motor: ldo-42sth48-2004mah
[autotune_tmc stepper_y]
motor: ldo-42sth48-2004mah

[autotune_tmc stepper_z]
motor: ldo-42sth40-1684cl350et
[autotune_tmc stepper_z1]
motor: ldo-42sth40-1684cl350et
[autotune_tmc stepper_z2]
motor: ldo-42sth40-1684cl350et

[autotune_tmc extruder]
motor: ldo-36sth20-1004ahg
```

Objects 1-3 left to right
![image](https://github.com/user-attachments/assets/bbc7f974-9061-436e-9727-0f10d964d2bc)

**Comment by MallocArray** [comment]
Unclear if my issues are related to this potential Klipper bug, exasperated by autotune, or unrelated entirely

https://klipper.discourse.group/t/bug-accumulating-microstep-shift-during-probe-moves-related-to-endstop-oversampling/19429/5

Host(aarch64, 32bit)
Version: v0.12.0-317-gb89d55238

Relevant Klipper config
```yaml
#####################################################################
#   Z Stepper Settings
#####################################################################

##  Z0 Stepper - Front Left
##  Connected to MOTOR_2
##  Endstop connected to DIAG_2
[stepper_z]
step_pin: PF11
dir_pin: !PG3
enable_pin: !PG5
rotation_distance: 4    # Rotation Distance for TR8x8 = 8, TR8x4 = 4, TR8x2 = 2
microsteps: 32
full_steps_per_rotation: 200
endstop_pin: PG10
# position_endstop = -1.300  # For ABS  -1.340 for PLA
position_max: 290
position_min: -2.5
homing_speed: 8.0 # Leadscrews are slower than 2.4, 10 is a recommended max.
second_homing_speed: 3
homing_retract_dist: 3

[tmc2209 stepper_z]
uart_pin: PC6
interpolate: False
run_current: 0.6
sense_resistor: 0.110
stealthchop_threshold: 0

##  Z1 Stepper - Rear Center
##  Connected to MOTOR_3
[stepper_z1]
step_pin: PG4
dir_pin: !PC1
enable_pin: !PA0
rotation_distance: 4  # Rotation Distance for TR8x8 = 8, TR8x4 = 4, TR8x2 = 2
microsteps: 32
full_steps_per_rotation: 200

##  Make sure to update below for your relevant driver (2208 or 2209)
[tmc2209 stepper_z1]
uart_pin: PC7
interpolate: False
run_current: 0.6
sense_resistor: 0.110
stealthchop_threshold: 0

##  Z2 Stepper - Front Right
##  Connected to MOTOR_4
[stepper_z2]
step_pin: PF9
dir_pin: !PF10
enable_pin: !PG2
rotation_distance: 4  # Rotation Distance for TR8x8 = 8, TR8x4 = 4, TR8x2 = 2
microsteps: 32
full_steps_per_rotation: 200

##  Make sure to update below for your relevant driver (2208 or 2209)
[tmc2209 stepper_z2]
uart_pin: PF2
interpolate: False
run_current: 0.6
sense_resistor: 0.110
stealthchop_threshold: 0

[probe]
##  Inductive Probe
##  This probe is not used for Z height, only Quad Gantry Leveling
## For the DIAG_7 port. NEEDS BAT85 DIODE! Change to !PG15 if probe is NO.
pin: ^PG15
x_offset: 0
y_offset: 25.0
z_offset: 0
speed: 10.0
samples: 3
samples_result: median
sample_retract_dist: 3.0
samples_tolerance: 0.006
samples_tolerance_retries: 3

```
