### ISSUE TITLE
Copy/pasteable config section with toggleable values

### ISSUE THREAD

**Issue by matthewbadeau** [andrewmcgr/klipper_tmc_autotune#39]
It's personal preference but I like copy/pasteable config sections where the options that can be toggled are explained in the section. This way, I don't need to move between screens/windows to see what I can configure. One blob with the defaults are nice. Like in the Klipper docs.

Consider adding something like this to the README. This is an issue, rather than a PR since I don't know your preference and that matters most.

```yaml
[autotune_tmc extruder]
# This parameter is used to retrieve the physical constants of the motor connected to the TMC driver
# Values: See DB
motor: ldo-36sth20-1004ahg
# Parameter to choose how to fine-tune the TMC driver using StealthChop and tailored parameters.
# By opting for auto, it will automatically apply performance for the X and Y axes and silent for the Z axis and extruder.
# autoswitch is an highly experimental choice that enables dynamic switching between silent and performance modes in real-time when needed.
# However, at the moment, this transition can potentially be troublesome, resulting in unwanted behavior, noise disturbances and lost steps. 
# Hence, it is recommended to avoid using 'autoswitch' until its identified issues are fully addressed
# Values: auto, silent, performance, and autoswitch
# Default: auto
tuning_goal: auto
# Additional hysteresis to reduce motor humming and vibration at low to medium speeds and maintain proper microstep accuracy.
# Warning: use only as much as necessary as a too high value will result in more chopper noise and motor power dissipation (ie. more heat)
# Values: 0 to 8
# Default: 0
extra_hysteresis: 0
# Comparator blank time. This time must safely cover the TMC switching events.
# A value of 1 or 2 should be fine for most typical applications, but higher capacitive loads may require this to be set to 3.
# Also, lower values allow StealthChop to regulate to lower coil current values
# Values: 0 to 3
# Default: 2
tbl: 2
# Sets the slow decay time (off time) of the chopper cycle. This setting also limits the maximum chopper frequency.
# When set to 0, the value is automatically computed by this autotuning algorithm. Highest motor velocities sometimes
# benefit from forcing toff to 1 or 2 and a setting a short tbl of 1 or 0
# Values: 0 to 15
# Default: 0
toff: 0
# Sensorless homing threshold for TMC5160, TMC2240, TMC2130, TMC2660. Set value appropriately if using
# sensorless homing (higher value means more sensitive detection and easier stall)
# Values: -64 to 63
# Default: 1
sgt: 1
# Sensorless homing threshold for TMC2209 and TMC2260. Set value appropriately if using sensorless homing
# (lower value means more sensitive detection and easier stall). This parameter is also used as the CoolStep current regulation
# threshold for TMC2209, TMC2240 and TMC5160. A default value of 80 is usually a good starting point for CoolStep (in the case of TMC2209,
# the tuned sensorless homing value will also work correctly)
# Values: 0 to 255
# Default: 10
sg4_thrs: 10
# Voltage used to power this motor and stepper driver
# Values: 0.0 to 60.0
# Default: 24
voltage: 24
# Set the optional overvoltage snubber built into the TMC2240 and TMC5160. Users of the BTT SB2240 toolhead board should use it
# for the extruder by reading the actual toolhead voltage and adding 0.8V
# Values: 0.0 to 60.0
# Default: 0.0
overvoltage_vth: 0.0
```
